### ISSUE TITLE
Error in getThreshold function

### ISSUE THREAD

**Issue by ThomasLuypaert** [Cdevenish/hardRain#1]
I was following the vignette for the classification of rain files on my own data, and ran into the following issues using the 'getThreshold' function:

**When using:** getThreshold(train.BR, fn = "spec")
**Error:** unused argument (fn = "spec")

**When just using:** getThreshold(train.BR)
**Error:** 1%Error in seq.default(1, n + 1 - wl, wl - (ovlp * wl/100)) : invalid '(to - from)/by'

**When using:** getThreshold(train.BR, freqLo = c(0.6, 4.4), freqHi = c(1.2, 5.6))
**Error:** 1%Error in seq.default(1, n + 1 - wl, wl - (ovlp * wl/100)):  invalid '(to - from)/by'

I was wondering what might be causing this issue, and how I can resolve it.

Cheers, 
Thomas

**Comment by Cdevenish** [comment]
The vignette referred to an older version of the package. It  should all be working with updates from some months ago. Let us know if you have any other issues.
